apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: client-deployment
  template:
    metadata:
      labels:
        app: client-deployment
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
          ports:
            - containerPort: {{ .Values.client.service.targetPort }}
          env:
            {{- range .Values.client.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
