apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client-deployment
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
      protocol: TCP
  type: {{ .Values.client.service.type }}