{{- range $componentName, $component := .Values.components }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $componentName }}-deployment
  {{- if $component.namespace }}
  namespace: {{ $component.namespace}}
  {{- end }}
spec:
  replicas: {{ $component.replicaCount }}
  selector:
    matchLabels:
      app: {{ $componentName }}-deployment
  template:
    metadata:
      labels:
        app: {{ $componentName }}-deployment
    spec:
      containers:
        - name: {{ $componentName }}
          image: "{{ $component.image.repository }}:{{ $component.image.tag }}"
          {{- if $component.args }}
          args:
            {{- range $arg := $component.args }}
            - {{ $arg | quote }}
            {{- end }}
          {{- end }}
          imagePullPolicy: {{ $component.image.pullPolicy }}
          resources:
            limits:
              cpu: "5000m"
              memory: "1024Mi"
            requests:
              cpu: "500m"
              memory: "1024Mi"
          ports:
            - containerPort: {{ $component.service.targetPort }}
          env:
            {{- range $component.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
            {{- range $component.envFromSecret }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKey }}
            {{- end }}
          volumeMounts:
            {{- range $component.volumes }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
            {{- end }}
      volumes:
        {{- range $component.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}-claim
        {{- end }}
        
---
{{- end }}
