apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-deployment
spec:
  replicas: {{ .Values.genai.replicaCount }}
  selector:
    matchLabels:
      app: genai-deployment
  template:
    metadata:
      labels:
        app: genai-deployment
    spec:
      containers:
        - name: genai
          image: "{{ .Values.genai.image.repository }}:{{ .Values.genai.image.tag }}"
          imagePullPolicy: {{ .Values.genai.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
          ports:
            - containerPort: {{ .Values.genai.service.targetPort }}
          env:
            {{- range .Values.genai.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
