apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-deployment
  ports:
    - port: {{ .Values.users.service.port }}
      targetPort: {{ .Values.users.service.targetPort }}
      protocol: TCP
  type: {{ .Values.users.service.type }}