apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: {{ .Values.users.replicaCount }}
  selector:
    matchLabels:
      app: users-deployment
  template:
    metadata:
      labels:
        app: users-deployment
    spec:
      containers:
        - name: users
          image: "{{ .Values.users.image.repository }}:{{ .Values.users.image.tag }}"
          imagePullPolicy: {{ .Values.users.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
          ports:
            - containerPort: {{ .Values.users.service.targetPort }}
          env:
            {{- range .Values.users.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
