services:
  client:
    image: ghcr.io/aet-devops25/team-it-works-on-my-machine/client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
        - ASSET_DIR=/usr/share/nginx/html
        - APP_PREFIX=PREFIX_
        - PREFIX_GH_CONNECTOR_URL=${GH_CONNECTOR_URL}
        - PREFIX_GH_OAUTH_CLIENT_ID=${GH_OAUTH_CLIENT_ID}
    ports:
      - "${CLIENT_PORT}:80"
    depends_on:
     - gh-connector
    restart: unless-stopped

  gh-connector:
    image: ghcr.io/aet-devops25/team-it-works-on-my-machine/gh-connector:latest
    build:
      context: ./gh-connector
      dockerfile: Dockerfile
    ports:
      - "${GH_CONNECTOR_PORT}:3000"
    environment:
      - CLIENT_URL=${CLIENT_URL}
      # Since we call container -> container we use the internal hostname
      - GENAI_URL=http://genai-python:${GENAI_PORT}
      - GH_OAUTH_CLIENT_ID=${GH_OAUTH_CLIENT_ID}
      - GH_OAUTH_CLIENT_SECRET=${GH_OAUTH_CLIENT_SECRET}
    restart: unless-stopped

  genai-python:
    image: ghcr.io/aet-devops25/team-it-works-on-my-machine/genai:latest
    build:
      context: ./genai
      dockerfile: Dockerfile
    ports:
      - "${GENAI_PORT}:3001"
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - GENAI_URL=${GENAI_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_URL=${QDRANT_URL}
    restart: unless-stopped

  users:
    image: ghcr.io/aet-devops25/team-it-works-on-my-machine/users:latest
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "${USERS_PORT}:3002"
    depends_on:
      - users-db
    environment:
      - USERS_DB_HOST=users-db
      - USERS_DB_USERNAME=${USERS_DB_USERNAME}
      - USERS_DB_PASSWORD=${USERS_DB_PASSWORD}
    restart: unless-stopped

  users-db:
    image: postgres:15-alpine
    ports:
      - "${USERS_DB_PORT}:5432"
    environment:
      -  POSTGRES_DB=users
      -  POSTGRES_USER=${USERS_DB_USERNAME}
      -  POSTGRES_PASSWORD=${USERS_DB_PASSWORD}
