services:
  client:
    image: ghcr.io/aet-devops25/team-it-works-on-my-machine/client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL:-http://localhost:8589}
    depends_on:
     - gh-connector
    restart: unless-stopped


  gh-connector:
    image: ghcr.io/aet-devops25/team-it-works-on-my-machine/gh-connector:latest
    build:
      context: ./gh-connector
      dockerfile: Dockerfile
    ports:
      - "8589:8589"
    restart: unless-stopped