global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "users"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["users:3002"]

  - job_name: "gh-connector"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["gh-connector:3000"]

  - job_name: "genai-python"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["genai-python:3001"]
