global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "users"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["TODO"]

  - job_name: "gh-connector"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["TODO"]

  - job_name: "genai-python"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["TODO"]
