global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "gh-connector"
    metrics_path: "/api/gh-connector/actuator/prometheus"
    static_configs:
      - targets: ["ghconnector-service.generic-namespace:3000"]

  - job_name: "genai-python"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["genai-service.generic-namespace:3001"]

  - job_name: "users"
    metrics_path: "/api/users/actuator/prometheus"
    static_configs:
      - targets: ["users-service.generic-namespace:3002"]
