global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "users"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["users-service.generic-namespace:3002"]

  - job_name: "gh-connector"
    metrics_path: "/ping"
    static_configs:
      - targets: ["ghconnector-service.generic-namespace:3000"]

  - job_name: "genai-python"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["genai-service.generic-namespace:3001"]
