# No changes needed below this line
namespace:
  create: false

ghconnector:
  image:
    repository: ghcr.io/aet-devops25/team-it-works-on-my-machine/gh-connector
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  replicaCount: 1
  env:
    - name: CLIENT_URL
      value: CLIENT_URL
    # Since we call container -> container we use the internal hostname
    - name: GENAI_URL
      value: http://genai-python:GENAI_PORT
    - name: GH_OAUTH_CLIENT_ID
      value: GH_OAUTH_CLIENT_ID
    - name: GH_OAUTH_CLIENT_SECRET
      value: GH_OAUTH_CLIENT_SECRET
    - name: GH_CONNECTOR_PREFIX
      value: /api/gh-connector

client:
  image:
    repository: ghcr.io/aet-devops25/team-it-works-on-my-machine/client
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  replicaCount: 1
  env:
    - name: ASSET_DIR
      value: /usr/share/nginx/html
    - name: APP_PREFIX
      value: PREFIX_
    - name: PREFIX_GH_CONNECTOR_URL
      value: GH_CONNECTOR_URL
    - name: PREFIX_GH_OAUTH_CLIENT_ID
      value: GH_OAUTH_CLIENT_ID

ingress:
  enabled: true
  className: "nginx"
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
