name: CI Client
run-name: Check Client Code
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"
          cache-dependency-path: "client/pnpm-lock.yaml"
      - name: Install dependencies
        run: pnpm install
      - name: Run Eslint
        run: pnpm run lint
      - name: Run Prettier
        run: pnpm run format:check
      - name: Run Tests
        run: pnpm run test
