name: CI GenAI
run-name: Check GenAI Code
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: genai
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv venv && .venv\Scripts\activate && uv pip install -r requirements.txt
      - name: Lint & typecheck code
        run: uvx ruff check && uvx ty check
