name: Deploy Docker Images

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: AWS
      url: 'https://client.${{ vars.EC2_PUBLIC_IP }}.nip.io' 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy Docker Compose File From Repo to VM Host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.EC2_PUBLIC_IP }}
          username: ${{ vars.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          source: "./compose.aws.yml"
          target: /home/${{ vars.AWS_EC2_USER }}

      - name: SSH to VM and Create .env.prod
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.EC2_PUBLIC_IP }}
          username: ${{ vars.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            rm .env.prod
            touch .env.prod

            echo "CLIENT_PORT=80" >> .env.prod
            echo "GH_CONNECTOR_PORT=3000" >> .env.prod
            echo "GENAI_PORT=3001" >> .env.prod
            echo "USER_PORT=3002" >> .env.prod
            echo "USER_DB_PORT=5432" >> .env.prod

            echo "CLIENT_URL=client.${{ vars.EC2_PUBLIC_IP }}.nip.io" >> .env.prod
            echo "GH_CONNECTOR_HOST=gh-connector.${{ vars.EC2_PUBLIC_IP }}.nip.io" >> .env.prod
            echo "GENAI_HOST=genai.${{ vars.EC2_PUBLIC_IP }}.nip.io" >> .env.prod
            echo "USER_HOST=user.${{ vars.EC2_PUBLIC_IP }}.nip.io" >> .env.prod

            echo "USER_DB_HOST=user-db.${{ vars.EC2_PUBLIC_IP }}.nip.io" >> .env.prod
            echo "USER_DB_USERNAME=${{ vars.USER_DB_USERNAME }}" >> .env.prod
            echo "USER_DB_PASSWORD=${{ secrets.USER_DB_PASSWORD }}" >> .env.prod

            echo "DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}" >> .env.prod
            echo "GITHUB_OAUTH_CLIENT_ID=${{ vars.GITHUB_OAUTH_CLIENT_ID }}" >> .env.prod
            echo "GITHUB_OAUTH_CLIENT_SECRET=${{ secrets.GITHUB_OAUTH_CLIENT_SECRET }}" >> .env.prod


      - name: SSH to VM and Execute Docker-Compose Up
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.EC2_PUBLIC_IP }}
          username: ${{ vars.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            echo "Logging into Docker registry..."
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            echo "Starting Docker Compose..."
            docker compose -f compose.aws.yml --env-file=.env.prod up --pull=always -d
