# .github/workflows/deploy.yml
name: Deploy
on: push

jobs:
  deployment:
    runs-on: "ubuntu-latest"
    environment:
      name: Kubernetes

    steps:
      - uses: actions/checkout@v1

      - name: "Deploy"
        uses: "deliverybot/helm@v1"
        with:
          release: "workflow-genie"
          namespace: "devops25-works-on-my-machine"
          chart: "workflowgenie"
          token: "${{ github.token }}"
          values: |
            name: foobar
          value-files: >-
            [
              "values.yaml", 
              "values.production.yaml"
            ]
        env:
          KUBECONFIG_FILE: "${{ secrets.KUBECONFIG }}"
